main: suppress -Werror=unused-result
gcc 14.2 + glibc 2.40 produces this warning, converted to an error,
which fails the build.

	setup.c: In function ‘setup_interactively’:
	setup.c:149:32: error: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
	  149 |                         (void) fgets(buf, sizeof(buf), stdin);
	      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	main.c: In function ‘print_setup_as_args’:
	main.c:454:24: error: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
	  454 |                 (void) fgets(buf, sizeof(buf), stdin);
	      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~